### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by darkclouder** [darkclouder/distiller#1]
## 0.3
- [ ] Drivers
    - [ ] FileDocument driver (each file is a document/row)
- [ ] Pipe locks
- [ ] Worker spirit requirements
    - [ ] Requirement system
    - [ ] Requirement-based scheduling
    - [ ] Automated worker spawning
- [ ] Remote task updates
    - [ ] Upload mechanism
    - [ ] Cascaded update
        - [ ] Workers request resources for task specifically
        - [ ] An already scheduled task uses the old definition, only the next execution not in the active execution tree uses the new definition
        - [ ] Therefore: version handling and multiple copies of different versions if there are still tasks having a running execution for an older version
- [ ] Status feedback
    - [ ] CLI blocking until target done
    - [ ] Python lib to remote start targets blocking until done and reading driver
    - [ ] Spirit progress feedback channel
- [ ] Web UI
    - [ ] Scheduling configuration
    - [ ] Show execution branches
    - [ ] Show current execution and progress
    - [ ] Create and edit job scripts
    - [ ] View casks
